### ISSUE TITLE
Unable to view reflection probes lights

### ISSUE THREAD

**Issue by ShaziyaXR** [Ayfel/PrefabLightmapping#19]

**Comment by ShaziyaXR** [comment]
I am trying to take the data of reflection probe but the script has not one i guess.

**Comment by Ayfel** [comment]
Hi @ShaziyaXR , unfortunately it is not possible to save reflection probes to prefabs due to how they are calculated and store in scene lighting data asset. However it is possible to calculate light probes at runtime, which can be leveraged to create a similar effect. This is not a feature that I have published yet as it is different from the functionality of this project and requires a bit more planning from the user. I have a script that takes the light probes in users prefabs (as well as the lights which have to be then included in the prefab) and calculates them at runtime. I am planning to add this to the project in the future but I have not a defined timeline yet since I want to think a bit on the best workflow.

**Comment by ShaziyaXR** [comment]
Thanks. But if this project has the reflection probes concept . I feel this would be amazing. Your code helped alot . thanks again.

**Comment by Ayfel** [comment]
Hi @ShaziyaXR , I have a version for lightprobes but I need to integrate it. Let me see if this week or next I can finish and include that in the project.
